variables:
  in_channels: &unet_in_channels 32
  latent_embed_dim: &latent_embed_dim 16
  latent_f_size: &latent_f_size 8 # must be 1/8 of mel_bins
  latent_t_size: &latent_t_size 128 # TODO might need to change
  mel_bins: &mel_bins 64
  optimize_ddpm_parameter: &optimize_ddpm_parameter true
  optimize_gpt: &optimize_gpt false
  sampling_rate: &sampling_rate 48000
  warmup_steps: &warmup_steps 5000
  dataset: &dataset "audiocaps_smol"
augmentation:
  mixup: 0.0
data:
  class_label_indices: "audioset_eval_subset"
  dataloader_add_ons: ["make_batch_for_super_resolution"]
  test: *dataset
  train: [*dataset]
  val: *dataset
log_directory: "./log/latent_diffusion"
metadata_root: "./data/dataset/metadata/dataset_root.json"
model:
  params:
    base_learning_rate: 0.0001
    batchsize: 2
    beta_schedule: cosine
    channels: *latent_embed_dim # TODO might need to change
    cond_stage_config:
      concat_lowpass_cond:
        cond_stage_key: lowpass_mel
        conditioning_key: concat
        params:
          first_stage_config:
            base_learning_rate: 8.0e-06
            params:
              batchsize: 4
              lossconfig:
                params:
                  disc_in_channels: 1
                  disc_start: 50001
                  disc_weight: 0.5
                  kl_weight: 1000.0
                target: audioldm_train.losses.LPIPSWithDiscriminator
              ddconfig:
                attn_resolutions: []
                ch: 128
                ch_mult:
                  - 1
                  - 2
                  - 4
                  - 8
                double_z: true
                downsample_time: false
                dropout: 0.1
                in_channels: 1
                mel_bins: *mel_bins
                num_res_blocks: 2
                out_ch: 1
                resolution: 256
                z_channels: 16
              embed_dim: *latent_embed_dim
              image_key: fbank
              monitor: val/rec_loss
              sampling_rate: *sampling_rate
              subband: 1
              time_shuffle: 1
            target: audioldm_train.modules.latent_encoder.autoencoder.AutoencoderKL
        target: audioldm_train.conditional_models.VAEFeatureExtract
    evaluation_params:
      ddim_sampling_steps: 10 # 10 for debug, 200 for real thing
      n_candidates_per_samples: 1
      unconditional_guidance_scale: 3.5
    # Autoencoder
    first_stage_config:
      base_learning_rate: 8.0e-06
      params:
        batchsize: 4
        ddconfig:
          attn_resolutions: []
          ch: 128
          ch_mult:
            - 1
            - 2
            - 4
            - 8
          double_z: true
          downsample_time: false
          dropout: 0.1
          in_channels: 1
          mel_bins: *mel_bins # The frequency bins of mel spectrogram
          num_res_blocks: 2
          out_ch: 1
          resolution: 256
          z_channels: 16
        embed_dim: *latent_embed_dim
        image_key: fbank
        lossconfig:
          params:
            disc_in_channels: 1
            disc_start: 50001
            disc_weight: 0.5
            kl_weight: 1000.0
          target: audioldm_train.losses.LPIPSWithDiscriminator
        monitor: val/rec_loss
        #reload_from_ckpt: /mnt/bn/lqhaoheliu/project/audio_generation_diffusion/log/vae/vae_48k_256/ds_8_kl_1/checkpoints/ckpt-checkpoint-484999.ckpt
        sampling_rate: *sampling_rate
        subband: 1
        time_shuffle: 1
      target: audioldm_train.modules.latent_encoder.autoencoder.AutoencoderKL
    first_stage_key: fbank
    latent_f_size: *latent_f_size
    latent_t_size: *latent_t_size # TODO might need to change
    linear_end: 0.0195
    linear_start: 0.0015
    log_every_t: 200
    monitor: val/loss_simple_ema
    num_timesteps_cond: 1
    optimize_ddpm_parameter: *optimize_ddpm_parameter
    parameterization: v
    sampling_rate: *sampling_rate
    scale_by_std: true
    timesteps: 1000
    unconditional_prob_cfg: 0.1
    unet_config:
      params:
        attention_resolutions:
          - 8
          - 4
          - 2
        channel_mult:
          - 1
          - 2
          - 3
          - 5
        extra_sa_layer: true
        image_size: 64
        in_channels: *unet_in_channels # The input channel of the UNet model
        model_channels: 128
        num_head_channels: 32
        num_res_blocks: 2
        out_channels: *latent_embed_dim # TODO might need to change
        transformer_depth: 1
        use_spatial_transformer: true
      target: audioldm_train.modules.diffusionmodules.openaimodel.UNetModel
    warmup_steps: *warmup_steps
  target: audioldm_train.modules.latent_diffusion.ddpm.LatentDiffusion
preprocessing:
  audio:
    duration: 10.24
    max_wav_value: 32768.0
    sampling_rate: *sampling_rate
  mel:
    mel_fmax: 24000
    mel_fmin: 20
    n_mel_channels: *mel_bins
  stft:
    filter_length: 2048
    hop_length: 480
    win_length: 2048
project: "audiosr_train"
step:
  # limit_val_batches: 2
  max_steps: 2000 # 800000
  save_checkpoint_every_n_steps: 1000 #5000
  save_top_k: 1
  validation_every_n_epochs: 1 #5
