metadata_root: "./data/dataset/metadata/dataset_root.json"
log_directory: "./log/latent_diffusion"
project: "audioldm"
precision: "high"


variables:
  sampling_rate: &sampling_rate 48000 
  mel_bins: &mel_bins 256
  latent_embed_dim: &latent_embed_dim 8
  latent_t_size: &latent_t_size 256 # TODO might need to change
  latent_f_size: &latent_f_size 16
  in_channels: &unet_in_channels 8
  optimize_ddpm_parameter: &optimize_ddpm_parameter true
  optimize_gpt: &optimize_gpt true
  warmup_steps: &warmup_steps 2000

data: 
  train: ["audiocaps"]
  val: "audiocaps"
  test: "audiocaps"
  class_label_indices: "audioset_eval_subset"
  dataloader_add_ons: [] 

step:
  validation_every_n_epochs: 5
  save_checkpoint_every_n_steps: 5000
  # limit_val_batches: 2
  max_steps: 800000
  save_top_k: 1

preprocessing:
  audio:
    sampling_rate: 48000
    max_wav_value: 32768.0
    duration: 10.24
  stft:
    filter_length: 2048
    hop_length: 480
    win_length: 2048
  mel:
    n_mel_channels: 256
    mel_fmin: 20
    mel_fmax: 24000 

augmentation:
  mixup: 0.5

model:
  target: audioldm_train.modules.latent_diffusion.ddpm.LatentDiffusion
  params: 
    # Autoencoder
    first_stage_config:
      base_learning_rate: 0.000008
      target: audioldm_train.modules.latent_encoder.autoencoder.AutoencoderKL
      params: 
        reload_from_ckpt: "data/checkpoints/vae_mel_16k_64bins.ckpt"
        sampling_rate: 48000
        batchsize: 4
        monitor: val/rec_loss
        image_key: fbank
        subband: 1
        embed_dim: 16
        time_shuffle: 1
        lossconfig:
          target: audioldm_train.losses.LPIPSWithDiscriminator
          params:
            disc_start: 50001
            kl_weight: 1000.0
            disc_weight: 0.5
            disc_in_channels: 1
        ddconfig: 
          double_z: true
          mel_bins:   256 # The frequency bins of mel spectrogram
          z_channels: 16
          resolution: 256
          downsample_time: false
          in_channels: 1
          out_ch: 1
          ch: 128 
          ch_mult:
          - 1
          - 2
          - 4
          - 8
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.1
    
    # Other parameters
    base_learning_rate:  0.0001
    warmup_steps: 5000
    optimize_ddpm_parameter: true
    sampling_rate: 48000
    batchsize: 16
    ####
    beta_schedule: cosine
    #####
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    unconditional_prob_cfg: 0.1
    parameterization:  v # [eps, x0, v]
    first_stage_key: fbank
    latent_t_size: 128 # TODO might need to change
    latent_f_size: 32
    channels: 16 # TODO might need to change
    monitor: val/loss_simple_ema
    scale_by_std: true
    unet_config:
      target: audioldm_train.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64 
        extra_film_condition_dim: 512 # If you use film as extra condition, set this parameter. For example if you have two conditioning vectors each have dimension 512, then this number would be 1024
        # context_dim: 
        # - 768
        in_channels: 32 # The input channel of the UNet model
        out_channels: 16 # TODO might need to change
        model_channels: 128 # TODO might need to change
        attention_resolutions:
        - 8
        - 4
        - 2
        num_res_blocks: 2
        channel_mult: 
        - 1
        - 2
        - 3
        - 5
        num_head_channels: 32
        use_spatial_transformer: true
        transformer_depth: 1
        extra_sa_layer: true
    
    cond_stage_config:
      concat_lowpass_cond:
        cond_stage_key: lowpass_mel
        conditioning_key: concat
        target: audiosr.latent_diffusion.modules.encoders.modules.VAEFeatureExtract
        params:
          first_stage_config: 
            base_learning_rate: 0.000008
            target: "audiosr.latent_encoder.autoencoder.AutoencoderKL"
            params: 
                sampling_rate: 48000
                batchsize: 4
                monitor: val/rec_loss
                image_key: fbank
                subband: 1
                embed_dim: 16
                time_shuffle: 1
                ddconfig: 
                    double_z: true
                    mel_bins: 256
                    z_channels: 16
                    resolution: 256
                    downsample_time: false
                    in_channels: 1
                    out_ch: 1
                    ch: 128
                    ch_mult: 
                    - 1
                    - 2
                    - 4 
                    - 8
                    num_res_blocks: 2
                    attn_resolutions: []
                    dropout: 0.1

    evaluation_params:
      unconditional_guidance_scale: 3.5
      ddim_sampling_steps: 200
      n_candidates_per_samples: 1
